/**
 * @author Lavelle Hatcher Jr
 * @copyright Copyright (c) 2025 Lavelle Hatcher Jr. All rights reserved.
 */

import { useTranslation } from 'react-i18next';
import {
  FileUp,
  Database,
  Filter,
  Columns,
  ArrowUpDown,
  Group,
  GitMerge,
  Plus,
  Eraser,
  BarChart3,
  TrendingUp,
  Network,
  PieChart,
  Table,
  Download,
  AlertCircle,
  CheckCircle,
  Loader2,
  PenLine,
  TextCursorInput,
  Copy,
  Shuffle,
  ListFilter,
  RotateCcw,
  RotateCw,
  Layers,
  Scissors,
  Combine,
  GitBranch,
  Minimize2,
  AlertTriangle,
  GitFork,
  Activity,
  FlaskConical,
  Clock,
  Award,
  Repeat,
  FileSearch,
  Hash,
  Grid3x3,
  Scale,
  Binary,
  Grid2x2,
  Music,
  LayoutGrid,
  AreaChart,
  Circle,
  ScatterChart,
  Users,
  Target,
  Calendar,
  Type,
  Waypoints,
  BarChart,
  Medal,
  RefreshCw,
  ArrowLeftRight,
  MoveHorizontal,
  CalendarRange,
  FlipHorizontal,
  AlignJustify,
  Link,
  MessageSquare,
  Split,
  ClipboardCheck,
  Brain,
  Rocket,
  CalendarClock,
  Percent,
  FileText,
  GitCompare,
  ListOrdered,
  Trophy,
  Sun,
  Gauge,
  Radar,
  Map,
  Cloud,
  CandlestickChart,
  AlignVerticalDistributeCenter,
  BoxSelect,
  Grid,
  MapPin,
  Layers3,
  Share2,
  CalendarDays,
  LayoutPanelLeft,
  Waves,
  AlertCircle as ErrorIcon,
  CircleDot,
  ArrowRightLeft,
  BarChart4,
  LineChart,
  Shield,
  Sigma,
  Settings,
  Code,
  DatabaseZap,
  FileBarChart,
  ShieldCheck,
  Cpu,
  Sparkles,
  Lightbulb,
  Wand2,
  FileCode,
  ScanSearch,
  TrendingDown,
  Save,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { BlockType, BlockState } from '@/types';

interface BlockHeaderProps {
  type: BlockType;
  label: string;
  state: BlockState;
  error?: string;
}

const icons: Record<string, LucideIcon> = {
  FileUp,
  Database,
  Filter,
  Columns,
  ArrowUpDown,
  Group,
  GitMerge,
  Plus,
  Eraser,
  BarChart3,
  TrendingUp,
  Network,
  PieChart,
  Table,
  Download,
  PenLine,
  TextCursorInput,
  Copy,
  Shuffle,
  ListFilter,
  RotateCcw,
  RotateCw,
  Layers,
  Scissors,
  Combine,
  GitBranch,
  Minimize2,
  AlertTriangle,
  GitFork,
  Activity,
  FlaskConical,
  Clock,
  Award,
  Repeat,
  FileSearch,
  Hash,
  Grid3x3,
  Scale,
  Binary,
  Grid2x2,
  Music,
  LayoutGrid,
  AreaChart,
  Circle,
  ScatterChart,
  Users,
  Target,
  Calendar,
  Type,
  Waypoints,
  BarChart,
  Medal,
  RefreshCw,
  ArrowLeftRight,
  MoveHorizontal,
  CalendarRange,
  FlipHorizontal,
  AlignJustify,
  Link,
  MessageSquare,
  Split,
  ClipboardCheck,
  Brain,
  Rocket,
  CalendarClock,
  Percent,
  FileText,
  GitCompare,
  ListOrdered,
  Trophy,
  Sun,
  Gauge,
  Radar,
  Map,
  Cloud,
  CandlestickChart,
  AlignVerticalDistributeCenter,
  BoxSelect,
  Grid,
  MapPin,
  Layers3,
  Share2,
  CalendarDays,
  LayoutPanelLeft,
  Waves,
  ErrorIcon,
  CircleDot,
  ArrowRightLeft,
  BarChart4,
  LineChart,
  Shield,
  Sigma,
  Settings,
  Code,
  DatabaseZap,
  FileBarChart,
  ShieldCheck,
  Cpu,
  Sparkles,
  Lightbulb,
  Wand2,
  FileCode,
  ScanSearch,
  TrendingDown,
  Save,
};

const iconMap: Record<BlockType, string> = {
  'load-data': 'FileUp',
  'sample-data': 'Database',
  'create-dataset': 'PenLine',
  'filter-rows': 'Filter',
  'select-columns': 'Columns',
  'sort': 'ArrowUpDown',
  'group-aggregate': 'Group',
  'join': 'GitMerge',
  'derive-column': 'Plus',
  'handle-missing': 'Eraser',
  'rename-columns': 'TextCursorInput',
  'deduplicate': 'Copy',
  'sample-rows': 'Shuffle',
  'limit-rows': 'ListFilter',
  'pivot': 'RotateCcw',
  'unpivot': 'RotateCw',
  'union': 'Layers',
  'split-column': 'Scissors',
  'merge-columns': 'Combine',
  'conditional-column': 'GitBranch',
  'datetime-extract': 'Calendar',
  'string-operations': 'Type',
  'window-functions': 'Waypoints',
  'bin-bucket': 'BarChart',
  'rank': 'Medal',
  'type-conversion': 'RefreshCw',
  'fill-forward-backward': 'ArrowLeftRight',
  'lag-lead': 'MoveHorizontal',
  'row-number': 'Hash',
  'date-difference': 'CalendarRange',
  'transpose': 'FlipHorizontal',
  'string-pad': 'AlignJustify',
  'cumulative-operations': 'TrendingUp',
  'replace-values': 'Replace',
  'percent-change': 'TrendingUp',
  'round-numbers': 'Hash',
  'percent-of-total': 'PieChart',
  'absolute-value': 'PlusSquare',
  'column-math': 'Calculator',
  'extract-substring': 'Scissors',
  'parse-date': 'CalendarCheck',
  'split-to-rows': 'SplitSquareVertical',
  'clip-values': 'Minimize2',
  'standardize-text': 'Type',
  'case-when': 'GitBranch',
  'explode-column': 'Expand',
  'add-constant-column': 'PlusSquare',
  'drop-columns': 'Trash2',
  'flatten-json': 'Layers',
  'coalesce-columns': 'Merge',
  'reorder-columns': 'ArrowUpDown',
  'trim-text': 'Eraser',
  'lookup-vlookup': 'Search',
  'cross-join': 'Grid3x3',
  'filter-expression': 'Code',
  'number-format': 'Hash',
  'extract-pattern': 'Regex',
  'log-transform': 'TrendingUp',
  'interpolate-missing': 'TrendingUp',
  'date-truncate': 'Calendar',
  'period-over-period': 'GitCompare',
  'hash-column': 'Hash',
  'expand-date-range': 'CalendarRange',
  'string-similarity': 'GitCompare',
  'generate-sequence': 'ListOrdered',
  'top-n-per-group': 'Trophy',
  'first-last-per-group': 'ListFilter',
  'one-hot-encode': 'Binary',
  'label-encode': 'Hash',
  'ordinal-encode': 'ListOrdered',
  'min-max-normalize': 'Scale',
  'z-score-standardize': 'Activity',
  'rolling-statistics': 'TrendingUp',
  'resample-timeseries': 'Clock',
  'regex-replace': 'Code',
  'expand-json-column': 'Layers',
  'add-unique-id': 'Hash',
  'missing-indicator': 'AlertTriangle',
  'quantile-transform': 'BarChart3',
  'statistics': 'BarChart3',
  'regression': 'TrendingUp',
  'clustering': 'Network',
  'pca': 'Minimize2',
  'outlier-detection': 'AlertTriangle',
  'classification': 'GitFork',
  'normality-test': 'Activity',
  'hypothesis-testing': 'FlaskConical',
  'time-series': 'Clock',
  'feature-importance': 'Award',
  'cross-validation': 'Repeat',
  'data-profiling': 'FileSearch',
  'value-counts': 'Hash',
  'cross-tabulation': 'Grid3x3',
  'scaling': 'Scale',
  'encoding': 'Binary',
  'ab-test': 'FlaskConical',
  'cohort-analysis': 'Users',
  'rfm-analysis': 'Target',
  'anova': 'BarChart3',
  'chi-square-test': 'Grid3x3',
  'correlation-analysis': 'Link',
  'survival-analysis': 'Activity',
  'association-rules': 'Network',
  'sentiment-analysis': 'MessageSquare',
  'moving-average': 'TrendingUp',
  'train-test-split': 'Split',
  'model-evaluation': 'ClipboardCheck',
  'knn': 'Users',
  'naive-bayes': 'Brain',
  'gradient-boosting': 'Rocket',
  'pareto-analysis': 'BarChart3',
  'trend-analysis': 'TrendingUp',
  'forecasting': 'CalendarClock',
  'percentile-analysis': 'Percent',
  'distribution-fit': 'Activity',
  'text-preprocessing': 'FileText',
  'tfidf-vectorization': 'Hash',
  'topic-modeling': 'Layers',
  'similarity-analysis': 'GitCompare',
  'svm': 'Target',
  'xgboost': 'Zap',
  'model-explainability': 'Lightbulb',
  'regression-diagnostics': 'Microscope',
  'vif-analysis': 'GitMerge',
  'funnel-analysis': 'Filter',
  'customer-ltv': 'DollarSign',
  'churn-analysis': 'UserMinus',
  'growth-metrics': 'TrendingUp',
  'attribution-modeling': 'GitBranch',
  'breakeven-analysis': 'Scale',
  'confidence-intervals': 'ArrowLeftRight',
  'bootstrap-analysis': 'RefreshCw',
  'posthoc-tests': 'GitCompare',
  'power-analysis': 'Gauge',
  'bayesian-inference': 'BarChart2',
  'data-quality-score': 'CheckCircle',
  'changepoint-detection': 'GitCommit',
  'isolation-forest': 'AlertTriangle',
  'arima-forecasting': 'TrendingUp',
  'seasonal-decomposition': 'Waves',
  'monte-carlo-simulation': 'Shuffle',
  'propensity-score-matching': 'Users',
  'difference-in-differences': 'GitCompare',
  'factor-analysis': 'Layers',
  'dbscan-clustering': 'Network',
  'elastic-net': 'TrendingUp',
  'var-analysis': 'Activity',
  'interrupted-time-series': 'Activity',
  'granger-causality': 'ArrowRightLeft',
  'local-outlier-factor': 'AlertTriangle',
  'feature-selection': 'Filter',
  'outlier-treatment': 'Shield',
  'data-drift': 'GitCompare',
  'polynomial-features': 'Sigma',
  'multi-output': 'GitFork',
  'probability-calibration': 'Gauge',
  'tsne-reduction': 'Minimize2',
  'statistical-tests': 'FlaskConical',
  'optimal-binning': 'BarChart',
  'correlation-finder': 'Link',
  'ab-test-calculator': 'FlaskConical',
  'target-encoding': 'Binary',
  'learning-curves': 'TrendingUp',
  'imbalanced-data-handler': 'Scale',
  'hyperparameter-tuning': 'Settings',
  'ensemble-stacking': 'Layers',
  'advanced-imputation': 'Eraser',
  'umap-reduction': 'Minimize2',
  'cluster-validation': 'CheckCircle',
  'model-comparison': 'GitCompare',
  'time-series-cv': 'Calendar',
  'uplift-modeling': 'TrendingUp',
  'quantile-regression': 'BarChart3',
  'adversarial-validation': 'AlertTriangle',
  'custom-python-code': 'Code',
  'sql-query': 'DatabaseZap',
  'auto-eda': 'FileBarChart',
  'data-validation': 'ShieldCheck',
  'neural-network': 'Cpu',
  'auto-feature-engineering': 'Sparkles',
  'shap-interpretation': 'Lightbulb',
  'automl': 'Wand2',
  'pipeline-export': 'FileCode',
  'multivariate-anomaly': 'ScanSearch',
  'causal-impact': 'TrendingDown',
  'model-registry': 'Save',
  'chart': 'PieChart',
  'table': 'Table',
  'correlation-matrix': 'Grid2x2',
  'violin-plot': 'Music',
  'pair-plot': 'LayoutGrid',
  'area-chart': 'AreaChart',
  'stacked-chart': 'Layers',
  'bubble-chart': 'Circle',
  'qq-plot': 'ScatterChart',
  'confusion-matrix': 'Grid3x3',
  'roc-curve': 'TrendingUp',
  'funnel-chart': 'Filter',
  'sankey-diagram': 'GitMerge',
  'treemap': 'LayoutGrid',
  'sunburst-chart': 'Sun',
  'gauge-chart': 'Gauge',
  'radar-chart': 'Radar',
  'waterfall-chart': 'BarChart3',
  'candlestick-chart': 'CandlestickChart',
  'choropleth-map': 'Map',
  'word-cloud': 'Cloud',
  'pareto-chart': 'BarChart3',
  'parallel-coordinates': 'AlignVerticalDistributeCenter',
  'dendrogram': 'GitFork',
  'box-plot': 'BoxSelect',
  'heatmap': 'Grid',
  'scatter-map': 'MapPin',
  'grouped-histogram': 'Layers3',
  'network-graph': 'Share2',
  'calendar-heatmap': 'CalendarDays',
  'faceted-chart': 'LayoutPanelLeft',
  'density-plot': 'Waves',
  'error-bar-chart': 'ErrorIcon',
  'dot-plot': 'CircleDot',
  'slope-chart': 'ArrowRightLeft',
  'grouped-bar-chart': 'BarChart4',
  'bump-chart': 'LineChart',
  'donut-chart': 'PieChart',
  'horizontal-bar-chart': 'BarChart',
  'scatter-3d': 'ScatterChart',
  'contour-plot': 'Waves',
  'hexbin-plot': 'Grid3x3',
  'ridge-plot': 'Layers',
  'strip-plot': 'CircleDot',
  'bullet-chart': 'Target',
  'pyramid-chart': 'BarChart3',
  'timeline-chart': 'Calendar',
  'surface-3d': 'Grid',
  'marginal-histogram': 'LayoutGrid',
  'dumbbell-chart': 'ArrowLeftRight',
  'export': 'Download',
};

// Map block types to translation keys
const blockTranslationKeys: Record<BlockType, string> = {
  'load-data': 'blocks.loadData',
  'sample-data': 'blocks.sampleData',
  'create-dataset': 'blocks.createDataset',
  'filter-rows': 'blocks.filterRows',
  'select-columns': 'blocks.selectColumns',
  'sort': 'blocks.sort',
  'group-aggregate': 'blocks.groupAggregate',
  'join': 'blocks.join',
  'derive-column': 'blocks.deriveColumn',
  'handle-missing': 'blocks.handleMissing',
  'rename-columns': 'blocks.renameColumns',
  'deduplicate': 'blocks.deduplicate',
  'sample-rows': 'blocks.sampleRows',
  'limit-rows': 'blocks.limitRows',
  'pivot': 'blocks.pivot',
  'unpivot': 'blocks.unpivot',
  'union': 'blocks.union',
  'split-column': 'blocks.splitColumn',
  'merge-columns': 'blocks.mergeColumns',
  'conditional-column': 'blocks.conditionalColumn',
  'datetime-extract': 'blocks.datetimeExtract',
  'string-operations': 'blocks.stringOperations',
  'window-functions': 'blocks.windowFunctions',
  'bin-bucket': 'blocks.binBucket',
  'rank': 'blocks.rank',
  'type-conversion': 'blocks.typeConversion',
  'fill-forward-backward': 'blocks.fillForwardBackward',
  'lag-lead': 'blocks.lagLead',
  'row-number': 'blocks.rowNumber',
  'date-difference': 'blocks.dateDifference',
  'transpose': 'blocks.transpose',
  'string-pad': 'blocks.stringPad',
  'cumulative-operations': 'blocks.cumulativeOperations',
  'replace-values': 'blocks.replaceValues',
  'percent-change': 'blocks.percentChange',
  'round-numbers': 'blocks.roundNumbers',
  'percent-of-total': 'blocks.percentOfTotal',
  'absolute-value': 'blocks.absoluteValue',
  'column-math': 'blocks.columnMath',
  'extract-substring': 'blocks.extractSubstring',
  'parse-date': 'blocks.parseDate',
  'split-to-rows': 'blocks.splitToRows',
  'clip-values': 'blocks.clipValues',
  'standardize-text': 'blocks.standardizeText',
  'case-when': 'blocks.caseWhen',
  'explode-column': 'blocks.explodeColumn',
  'add-constant-column': 'blocks.addConstantColumn',
  'drop-columns': 'blocks.dropColumns',
  'flatten-json': 'blocks.flattenJson',
  'coalesce-columns': 'blocks.coalesceColumns',
  'reorder-columns': 'blocks.reorderColumns',
  'trim-text': 'blocks.trimText',
  'lookup-vlookup': 'blocks.lookupVlookup',
  'cross-join': 'blocks.crossJoin',
  'filter-expression': 'blocks.filterExpression',
  'number-format': 'blocks.numberFormat',
  'extract-pattern': 'blocks.extractPattern',
  'log-transform': 'blocks.logTransform',
  'interpolate-missing': 'blocks.interpolateMissing',
  'date-truncate': 'blocks.dateTruncate',
  'period-over-period': 'blocks.periodOverPeriod',
  'hash-column': 'blocks.hashColumn',
  'expand-date-range': 'blocks.expandDateRange',
  'string-similarity': 'blocks.stringSimilarity',
  'generate-sequence': 'blocks.generateSequence',
  'top-n-per-group': 'blocks.topNPerGroup',
  'first-last-per-group': 'blocks.firstLastPerGroup',
  'one-hot-encode': 'blocks.oneHotEncode',
  'label-encode': 'blocks.labelEncode',
  'ordinal-encode': 'blocks.ordinalEncode',
  'min-max-normalize': 'blocks.minMaxNormalize',
  'z-score-standardize': 'blocks.zScoreStandardize',
  'rolling-statistics': 'blocks.rollingStatistics',
  'resample-timeseries': 'blocks.resampleTimeseries',
  'regex-replace': 'blocks.regexReplace',
  'expand-json-column': 'blocks.expandJsonColumn',
  'add-unique-id': 'blocks.addUniqueId',
  'missing-indicator': 'blocks.missingIndicator',
  'quantile-transform': 'blocks.quantileTransform',
  'statistics': 'blocks.statistics',
  'regression': 'blocks.regression',
  'clustering': 'blocks.clustering',
  'pca': 'blocks.pca',
  'outlier-detection': 'blocks.outlierDetection',
  'classification': 'blocks.classification',
  'normality-test': 'blocks.normalityTest',
  'hypothesis-testing': 'blocks.hypothesisTesting',
  'time-series': 'blocks.timeSeries',
  'feature-importance': 'blocks.featureImportance',
  'cross-validation': 'blocks.crossValidation',
  'data-profiling': 'blocks.dataProfiling',
  'value-counts': 'blocks.valueCounts',
  'cross-tabulation': 'blocks.crossTabulation',
  'scaling': 'blocks.scaling',
  'encoding': 'blocks.encoding',
  'ab-test': 'blocks.abTest',
  'cohort-analysis': 'blocks.cohortAnalysis',
  'rfm-analysis': 'blocks.rfmAnalysis',
  'anova': 'blocks.anova',
  'chi-square-test': 'blocks.chiSquareTest',
  'correlation-analysis': 'blocks.correlationAnalysis',
  'survival-analysis': 'blocks.survivalAnalysis',
  'association-rules': 'blocks.associationRules',
  'sentiment-analysis': 'blocks.sentimentAnalysis',
  'moving-average': 'blocks.movingAverage',
  'train-test-split': 'blocks.trainTestSplit',
  'model-evaluation': 'blocks.modelEvaluation',
  'knn': 'blocks.knn',
  'naive-bayes': 'blocks.naiveBayes',
  'gradient-boosting': 'blocks.gradientBoosting',
  'pareto-analysis': 'blocks.paretoAnalysis',
  'trend-analysis': 'blocks.trendAnalysis',
  'forecasting': 'blocks.forecasting',
  'percentile-analysis': 'blocks.percentileAnalysis',
  'distribution-fit': 'blocks.distributionFit',
  'text-preprocessing': 'blocks.textPreprocessing',
  'tfidf-vectorization': 'blocks.tfidfVectorization',
  'topic-modeling': 'blocks.topicModeling',
  'similarity-analysis': 'blocks.similarityAnalysis',
  'svm': 'blocks.svm',
  'xgboost': 'blocks.xgboost',
  'model-explainability': 'blocks.modelExplainability',
  'regression-diagnostics': 'blocks.regressionDiagnostics',
  'vif-analysis': 'blocks.vifAnalysis',
  'funnel-analysis': 'blocks.funnelAnalysis',
  'customer-ltv': 'blocks.customerLtv',
  'churn-analysis': 'blocks.churnAnalysis',
  'growth-metrics': 'blocks.growthMetrics',
  'attribution-modeling': 'blocks.attributionModeling',
  'breakeven-analysis': 'blocks.breakevenAnalysis',
  'confidence-intervals': 'blocks.confidenceIntervals',
  'bootstrap-analysis': 'blocks.bootstrapAnalysis',
  'posthoc-tests': 'blocks.posthocTests',
  'power-analysis': 'blocks.powerAnalysis',
  'bayesian-inference': 'blocks.bayesianInference',
  'data-quality-score': 'blocks.dataQualityScore',
  'changepoint-detection': 'blocks.changepointDetection',
  'isolation-forest': 'blocks.isolationForest',
  'arima-forecasting': 'blocks.arimaForecasting',
  'seasonal-decomposition': 'blocks.seasonalDecomposition',
  'monte-carlo-simulation': 'blocks.monteCarloSimulation',
  'propensity-score-matching': 'blocks.propensityScoreMatching',
  'difference-in-differences': 'blocks.differenceInDifferences',
  'factor-analysis': 'blocks.factorAnalysis',
  'dbscan-clustering': 'blocks.dbscanClustering',
  'elastic-net': 'blocks.elasticNet',
  'var-analysis': 'blocks.varAnalysis',
  'interrupted-time-series': 'blocks.interruptedTimeSeries',
  'granger-causality': 'blocks.grangerCausality',
  'local-outlier-factor': 'blocks.localOutlierFactor',
  'feature-selection': 'blocks.featureSelection',
  'outlier-treatment': 'blocks.outlierTreatment',
  'data-drift': 'blocks.dataDrift',
  'polynomial-features': 'blocks.polynomialFeatures',
  'multi-output': 'blocks.multiOutput',
  'probability-calibration': 'blocks.probabilityCalibration',
  'tsne-reduction': 'blocks.tsneReduction',
  'statistical-tests': 'blocks.statisticalTests',
  'optimal-binning': 'blocks.optimalBinning',
  'correlation-finder': 'blocks.correlationFinder',
  'ab-test-calculator': 'blocks.abTestCalculator',
  'target-encoding': 'blocks.targetEncoding',
  'learning-curves': 'blocks.learningCurves',
  'imbalanced-data-handler': 'blocks.imbalancedDataHandler',
  'hyperparameter-tuning': 'blocks.hyperparameterTuning',
  'ensemble-stacking': 'blocks.ensembleStacking',
  'advanced-imputation': 'blocks.advancedImputation',
  'umap-reduction': 'blocks.umapReduction',
  'cluster-validation': 'blocks.clusterValidation',
  'model-comparison': 'blocks.modelComparison',
  'time-series-cv': 'blocks.timeSeriesCv',
  'uplift-modeling': 'blocks.upliftModeling',
  'quantile-regression': 'blocks.quantileRegression',
  'adversarial-validation': 'blocks.adversarialValidation',
  'custom-python-code': 'blocks.customPythonCode',
  'sql-query': 'blocks.sqlQuery',
  'auto-eda': 'blocks.autoEda',
  'data-validation': 'blocks.dataValidation',
  'neural-network': 'blocks.neuralNetwork',
  'auto-feature-engineering': 'blocks.autoFeatureEngineering',
  'shap-interpretation': 'blocks.shapInterpretation',
  'automl': 'blocks.automl',
  'pipeline-export': 'blocks.pipelineExport',
  'multivariate-anomaly': 'blocks.multivariateAnomaly',
  'causal-impact': 'blocks.causalImpact',
  'model-registry': 'blocks.modelRegistry',
  'chart': 'blocks.chart',
  'table': 'blocks.table',
  'correlation-matrix': 'blocks.correlationMatrix',
  'violin-plot': 'blocks.violinPlot',
  'pair-plot': 'blocks.pairPlot',
  'area-chart': 'blocks.areaChart',
  'stacked-chart': 'blocks.stackedChart',
  'bubble-chart': 'blocks.bubbleChart',
  'qq-plot': 'blocks.qqPlot',
  'confusion-matrix': 'blocks.confusionMatrix',
  'roc-curve': 'blocks.rocCurve',
  'funnel-chart': 'blocks.funnelChart',
  'sankey-diagram': 'blocks.sankeyDiagram',
  'treemap': 'blocks.treemap',
  'sunburst-chart': 'blocks.sunburstChart',
  'gauge-chart': 'blocks.gaugeChart',
  'radar-chart': 'blocks.radarChart',
  'waterfall-chart': 'blocks.waterfallChart',
  'candlestick-chart': 'blocks.candlestickChart',
  'choropleth-map': 'blocks.choroplethMap',
  'word-cloud': 'blocks.wordCloud',
  'pareto-chart': 'blocks.paretoChart',
  'parallel-coordinates': 'blocks.parallelCoordinates',
  'dendrogram': 'blocks.dendrogram',
  'box-plot': 'blocks.boxPlot',
  'heatmap': 'blocks.heatmap',
  'scatter-map': 'blocks.scatterMap',
  'grouped-histogram': 'blocks.groupedHistogram',
  'network-graph': 'blocks.networkGraph',
  'calendar-heatmap': 'blocks.calendarHeatmap',
  'faceted-chart': 'blocks.facetedChart',
  'density-plot': 'blocks.densityPlot',
  'error-bar-chart': 'blocks.errorBarChart',
  'dot-plot': 'blocks.dotPlot',
  'slope-chart': 'blocks.slopeChart',
  'grouped-bar-chart': 'blocks.groupedBarChart',
  'bump-chart': 'blocks.bumpChart',
  'donut-chart': 'blocks.donutChart',
  'horizontal-bar-chart': 'blocks.horizontalBarChart',
  'scatter-3d': 'blocks.scatter3d',
  'contour-plot': 'blocks.contourPlot',
  'hexbin-plot': 'blocks.hexbinPlot',
  'ridge-plot': 'blocks.ridgePlot',
  'strip-plot': 'blocks.stripPlot',
  'bullet-chart': 'blocks.bulletChart',
  'pyramid-chart': 'blocks.pyramidChart',
  'timeline-chart': 'blocks.timelineChart',
  'surface-3d': 'blocks.surface3d',
  'marginal-histogram': 'blocks.marginalHistogram',
  'dumbbell-chart': 'blocks.dumbbellChart',
  'export': 'blocks.export',
};

export function BlockHeader({ type, label, state, error }: BlockHeaderProps) {
  const { t } = useTranslation();
  const iconName = iconMap[type];
  const IconComponent = icons[iconName] || Database;

  // Use translated label, falling back to the original label if no translation exists
  const translatedLabel = t(blockTranslationKeys[type], { defaultValue: label });

  return (
    <div className="flex items-center gap-2 px-3 py-2 border-b border-border-default">
      <IconComponent size={16} className="text-text-muted" />
      <span className="text-small font-medium text-text-primary flex-1 truncate">
        {translatedLabel}
      </span>
      {state === 'executing' && (
        <Loader2 size={14} className="animate-spin text-electric-indigo" />
      )}
      {state === 'success' && (
        <CheckCircle size={14} className="text-fresh-teal" />
      )}
      {state === 'error' && (
        <span title={error}>
          <AlertCircle size={14} className="text-warm-coral" />
        </span>
      )}
    </div>
  );
}
