/**
 * @author Lavelle Hatcher Jr
 * @copyright Copyright (c) 2025 Lavelle Hatcher Jr. All rights reserved.
 */

import { create } from 'zustand';
import { temporal } from 'zundo';
import { v4 as uuidv4 } from 'uuid';
import type { PipelineBlock, PipelineEdge, BlockData, BlockState, BlockType, BlockCategory } from '@/types';

interface CanvasState {
  blocks: PipelineBlock[];
  edges: PipelineEdge[];
  selectedBlockIds: string[];
  viewport: { x: number; y: number; zoom: number };

  // Actions
  addBlock: (type: BlockType, position: { x: number; y: number }) => string;
  addBlockDirect: (block: PipelineBlock) => void;
  updateBlock: (id: string, data: Partial<BlockData>) => void;
  removeBlock: (id: string) => void;
  setBlockState: (id: string, state: BlockState) => void;

  addEdge: (source: string, target: string, sourceHandle?: string, targetHandle?: string) => void;
  addEdgeDirect: (edge: PipelineEdge) => void;
  removeEdge: (id: string) => void;

  setBlocks: (blocks: PipelineBlock[]) => void;
  setEdges: (edges: PipelineEdge[]) => void;

  setSelectedBlocks: (ids: string[]) => void;
  clearSelection: () => void;

  setViewport: (viewport: { x: number; y: number; zoom: number }) => void;

  importPipeline: (blocks: PipelineBlock[], edges: PipelineEdge[]) => void;
  clearCanvas: () => void;
}

function getBlockCategory(type: BlockType): BlockCategory {
  const categories: Record<BlockType, BlockCategory> = {
    'load-data': 'data-input',
    'sample-data': 'data-input',
    'create-dataset': 'data-input',
    'filter-rows': 'transform',
    'select-columns': 'transform',
    'sort': 'transform',
    'group-aggregate': 'transform',
    'join': 'transform',
    'derive-column': 'transform',
    'handle-missing': 'transform',
    'rename-columns': 'transform',
    'deduplicate': 'transform',
    'sample-rows': 'transform',
    'limit-rows': 'transform',
    'pivot': 'transform',
    'unpivot': 'transform',
    'union': 'transform',
    'split-column': 'transform',
    'merge-columns': 'transform',
    'conditional-column': 'transform',
    'datetime-extract': 'transform',
    'string-operations': 'transform',
    'window-functions': 'transform',
    'bin-bucket': 'transform',
    'rank': 'transform',
    'type-conversion': 'transform',
    'fill-forward-backward': 'transform',
    'lag-lead': 'transform',
    'row-number': 'transform',
    'date-difference': 'transform',
    'transpose': 'transform',
    'string-pad': 'transform',
    'cumulative-operations': 'transform',
    'replace-values': 'transform',
    'percent-change': 'transform',
    'round-numbers': 'transform',
    'percent-of-total': 'transform',
    'absolute-value': 'transform',
    'column-math': 'transform',
    'extract-substring': 'transform',
    'parse-date': 'transform',
    'split-to-rows': 'transform',
    'clip-values': 'transform',
    'standardize-text': 'transform',
    'case-when': 'transform',
    'explode-column': 'transform',
    'add-constant-column': 'transform',
    'drop-columns': 'transform',
    'flatten-json': 'transform',
    'coalesce-columns': 'transform',
    'reorder-columns': 'transform',
    'trim-text': 'transform',
    'lookup-vlookup': 'transform',
    'cross-join': 'transform',
    'filter-expression': 'transform',
    'number-format': 'transform',
    'extract-pattern': 'transform',
    'log-transform': 'transform',
    'interpolate-missing': 'transform',
    'date-truncate': 'transform',
    'period-over-period': 'transform',
    'hash-column': 'transform',
    'expand-date-range': 'transform',
    'string-similarity': 'transform',
    'generate-sequence': 'transform',
    'top-n-per-group': 'transform',
    'first-last-per-group': 'transform',
    'one-hot-encode': 'transform',
    'label-encode': 'transform',
    'ordinal-encode': 'transform',
    'min-max-normalize': 'transform',
    'z-score-standardize': 'transform',
    'rolling-statistics': 'transform',
    'resample-timeseries': 'transform',
    'regex-replace': 'transform',
    'expand-json-column': 'transform',
    'add-unique-id': 'transform',
    'missing-indicator': 'transform',
    'quantile-transform': 'transform',
    // New Data Science Transform Blocks
    'fuzzy-join': 'transform',
    'memory-optimizer': 'transform',
    'cyclical-time-encoder': 'transform',
    'geographic-distance': 'transform',
    'rare-category-combiner': 'transform',
    'smart-auto-cleaner': 'transform',
    'interaction-generator': 'transform',
    'fuzzy-deduplicator': 'transform',
    'array-aggregator': 'transform',
    'target-aware-binning': 'transform',
    'statistics': 'analysis',
    'regression': 'analysis',
    'clustering': 'analysis',
    'pca': 'analysis',
    'outlier-detection': 'analysis',
    'classification': 'analysis',
    'normality-test': 'analysis',
    'hypothesis-testing': 'analysis',
    'time-series': 'analysis',
    'feature-importance': 'analysis',
    'cross-validation': 'analysis',
    'data-profiling': 'analysis',
    'value-counts': 'analysis',
    'cross-tabulation': 'analysis',
    'scaling': 'analysis',
    'encoding': 'analysis',
    'ab-test': 'analysis',
    'cohort-analysis': 'analysis',
    'rfm-analysis': 'analysis',
    'anova': 'analysis',
    'chi-square-test': 'analysis',
    'correlation-analysis': 'analysis',
    'survival-analysis': 'analysis',
    'association-rules': 'analysis',
    'sentiment-analysis': 'analysis',
    'moving-average': 'analysis',
    'train-test-split': 'analysis',
    'model-evaluation': 'analysis',
    'knn': 'analysis',
    'naive-bayes': 'analysis',
    'gradient-boosting': 'analysis',
    'pareto-analysis': 'analysis',
    'trend-analysis': 'analysis',
    'forecasting': 'analysis',
    'percentile-analysis': 'analysis',
    'distribution-fit': 'analysis',
    'text-preprocessing': 'analysis',
    'tfidf-vectorization': 'analysis',
    'topic-modeling': 'analysis',
    'similarity-analysis': 'analysis',
    'svm': 'analysis',
    'xgboost': 'analysis',
    'model-explainability': 'analysis',
    'regression-diagnostics': 'analysis',
    'vif-analysis': 'analysis',
    'funnel-analysis': 'analysis',
    'customer-ltv': 'analysis',
    'churn-analysis': 'analysis',
    'growth-metrics': 'analysis',
    'attribution-modeling': 'analysis',
    'breakeven-analysis': 'analysis',
    'confidence-intervals': 'analysis',
    'bootstrap-analysis': 'analysis',
    'posthoc-tests': 'analysis',
    'power-analysis': 'analysis',
    'bayesian-inference': 'analysis',
    'data-quality-score': 'analysis',
    'changepoint-detection': 'analysis',
    'isolation-forest': 'analysis',
    'arima-forecasting': 'analysis',
    'seasonal-decomposition': 'analysis',
    'monte-carlo-simulation': 'analysis',
    'propensity-score-matching': 'analysis',
    'difference-in-differences': 'analysis',
    'factor-analysis': 'analysis',
    'dbscan-clustering': 'analysis',
    'elastic-net': 'analysis',
    'var-analysis': 'analysis',
    'interrupted-time-series': 'analysis',
    'granger-causality': 'analysis',
    'local-outlier-factor': 'analysis',
    'feature-selection': 'analysis',
    'outlier-treatment': 'analysis',
    'data-drift': 'analysis',
    'polynomial-features': 'analysis',
    'multi-output': 'analysis',
    'probability-calibration': 'analysis',
    'tsne-reduction': 'analysis',
    'statistical-tests': 'analysis',
    'optimal-binning': 'analysis',
    'correlation-finder': 'analysis',
    'ab-test-calculator': 'analysis',
    'target-encoding': 'analysis',
    'learning-curves': 'analysis',
    'imbalanced-data-handler': 'analysis',
    'hyperparameter-tuning': 'analysis',
    'ensemble-stacking': 'analysis',
    'advanced-imputation': 'analysis',
    'umap-reduction': 'analysis',
    'cluster-validation': 'analysis',
    'model-comparison': 'analysis',
    'time-series-cv': 'analysis',
    'uplift-modeling': 'analysis',
    'quantile-regression': 'analysis',
    'adversarial-validation': 'analysis',
    'custom-python-code': 'analysis',
    'sql-query': 'analysis',
    'auto-eda': 'analysis',
    'data-validation': 'analysis',
    'neural-network': 'analysis',
    'auto-feature-engineering': 'analysis',
    'shap-interpretation': 'analysis',
    'automl': 'analysis',
    'pipeline-export': 'output',
    'multivariate-anomaly': 'analysis',
    'causal-impact': 'analysis',
    'model-registry': 'analysis',
    // New Advanced Analysis Blocks for Data Scientists
    'comprehensive-eda': 'analysis',
    'shap-deep-explainer': 'analysis',
    'stl-decomposition': 'analysis',
    'multi-algorithm-anomaly': 'analysis',
    'automated-feature-pipeline': 'analysis',
    'distribution-drift-monitor': 'analysis',
    'smart-resampling': 'analysis',
    'collinearity-diagnostics': 'analysis',
    'bayesian-ab-calculator': 'analysis',
    'nested-cross-validation': 'analysis',
    // New Pyodide-Compatible Analysis Blocks (December 2025)
    'gaussian-mixture-model': 'analysis',
    'dynamic-time-warping': 'analysis',
    'lime-explainer': 'analysis',
    'bayesian-optimization': 'analysis',
    'time-series-features': 'analysis',
    'robust-regression': 'analysis',
    'kernel-density-estimation': 'analysis',
    'spectral-clustering': 'analysis',
    'cross-correlation': 'analysis',
    'manifold-learning': 'analysis',
    // New Advanced Analysis Blocks (December 2025 - Batch 2)
    'semi-supervised-learning': 'analysis',
    'multi-label-classification': 'analysis',
    'conformal-prediction': 'analysis',
    'one-class-svm': 'analysis',
    'elliptic-envelope': 'analysis',
    'isotonic-regression': 'analysis',
    'power-transform': 'analysis',
    'mutual-information-selection': 'analysis',
    'sequential-feature-selection': 'analysis',
    'permutation-importance': 'analysis',
    'acf-pacf-analysis': 'analysis',
    'stationarity-testing': 'analysis',
    'exponential-smoothing': 'analysis',
    'copula-analysis': 'analysis',
    'variance-threshold': 'analysis',
    'hierarchical-clustering': 'analysis',
    'chart': 'visualization',
    'table': 'visualization',
    'correlation-matrix': 'visualization',
    'violin-plot': 'visualization',
    'pair-plot': 'visualization',
    'area-chart': 'visualization',
    'stacked-chart': 'visualization',
    'bubble-chart': 'visualization',
    'qq-plot': 'visualization',
    'confusion-matrix': 'visualization',
    'roc-curve': 'visualization',
    'funnel-chart': 'visualization',
    'sankey-diagram': 'visualization',
    'treemap': 'visualization',
    'sunburst-chart': 'visualization',
    'gauge-chart': 'visualization',
    'radar-chart': 'visualization',
    'waterfall-chart': 'visualization',
    'candlestick-chart': 'visualization',
    'choropleth-map': 'visualization',
    'word-cloud': 'visualization',
    'pareto-chart': 'visualization',
    'parallel-coordinates': 'visualization',
    'dendrogram': 'visualization',
    'box-plot': 'visualization',
    'heatmap': 'visualization',
    'scatter-map': 'visualization',
    'grouped-histogram': 'visualization',
    'network-graph': 'visualization',
    'calendar-heatmap': 'visualization',
    'faceted-chart': 'visualization',
    'density-plot': 'visualization',
    'error-bar-chart': 'visualization',
    'dot-plot': 'visualization',
    'slope-chart': 'visualization',
    'grouped-bar-chart': 'visualization',
    'bump-chart': 'visualization',
    'donut-chart': 'visualization',
    'horizontal-bar-chart': 'visualization',
    'scatter-3d': 'visualization',
    'contour-plot': 'visualization',
    'hexbin-plot': 'visualization',
    'ridge-plot': 'visualization',
    'strip-plot': 'visualization',
    'bullet-chart': 'visualization',
    'pyramid-chart': 'visualization',
    'timeline-chart': 'visualization',
    'surface-3d': 'visualization',
    'marginal-histogram': 'visualization',
    'dumbbell-chart': 'visualization',
    // New Advanced Visualization Blocks for Data Scientists
    'shap-summary-plot': 'visualization',
    'partial-dependence-plot': 'visualization',
    'feature-importance-plot': 'visualization',
    'ice-plot': 'visualization',
    'precision-recall-curve': 'visualization',
    'learning-curve-plot': 'visualization',
    'residual-plot': 'visualization',
    'actual-vs-predicted-plot': 'visualization',
    'calibration-curve': 'visualization',
    'lift-chart': 'visualization',
    'elbow-plot': 'visualization',
    'silhouette-plot': 'visualization',
    'tsne-umap-plot': 'visualization',
    'missing-value-heatmap': 'visualization',
    'outlier-detection-plot': 'visualization',
    'distribution-comparison-plot': 'visualization',
    'ecdf-plot': 'visualization',
    'andrews-curves': 'visualization',
    'cv-results-plot': 'visualization',
    'hyperparameter-heatmap': 'visualization',
    'export': 'output',
  };
  return categories[type];
}

function getBlockLabel(type: BlockType): string {
  const labels: Record<BlockType, string> = {
    'load-data': 'Load Data',
    'sample-data': 'Sample Data',
    'create-dataset': 'Create Dataset',
    'filter-rows': 'Filter Rows',
    'select-columns': 'Select Columns',
    'sort': 'Sort',
    'group-aggregate': 'Group & Aggregate',
    'join': 'Join',
    'derive-column': 'Derive Column',
    'handle-missing': 'Handle Missing',
    'rename-columns': 'Rename Columns',
    'deduplicate': 'Deduplicate',
    'sample-rows': 'Sample Rows',
    'limit-rows': 'Limit Rows',
    'pivot': 'Pivot',
    'unpivot': 'Unpivot',
    'union': 'Union',
    'split-column': 'Split Column',
    'merge-columns': 'Merge Columns',
    'conditional-column': 'Conditional Column',
    'datetime-extract': 'Date/Time Extract',
    'string-operations': 'String Operations',
    'window-functions': 'Window Functions',
    'bin-bucket': 'Bin/Bucket',
    'rank': 'Rank',
    'type-conversion': 'Type Conversion',
    'fill-forward-backward': 'Fill Forward/Backward',
    'lag-lead': 'Lag/Lead',
    'row-number': 'Row Number',
    'date-difference': 'Date Difference',
    'transpose': 'Transpose',
    'string-pad': 'String Pad',
    'cumulative-operations': 'Cumulative Operations',
    'replace-values': 'Replace Values',
    'percent-change': 'Percent Change',
    'round-numbers': 'Round Numbers',
    'percent-of-total': 'Percent of Total',
    'absolute-value': 'Absolute Value',
    'column-math': 'Column Math',
    'extract-substring': 'Extract Substring',
    'parse-date': 'Parse Date',
    'split-to-rows': 'Split to Rows',
    'clip-values': 'Clip Values',
    'standardize-text': 'Standardize Text',
    'case-when': 'Case When',
    'explode-column': 'Explode Column',
    'add-constant-column': 'Add Constant Column',
    'drop-columns': 'Drop Columns',
    'flatten-json': 'Flatten JSON',
    'coalesce-columns': 'Coalesce Columns',
    'reorder-columns': 'Reorder Columns',
    'trim-text': 'Trim & Clean Text',
    'lookup-vlookup': 'Lookup (VLOOKUP)',
    'cross-join': 'Cross Join',
    'filter-expression': 'Filter by Expression',
    'number-format': 'Number Format',
    'extract-pattern': 'Extract Pattern',
    'log-transform': 'Log Transform',
    'interpolate-missing': 'Interpolate Missing',
    'date-truncate': 'Date Truncate',
    'period-over-period': 'Period over Period',
    'hash-column': 'Hash Column',
    'expand-date-range': 'Expand Date Range',
    'string-similarity': 'String Similarity',
    'generate-sequence': 'Generate Sequence',
    'top-n-per-group': 'Top N per Group',
    'first-last-per-group': 'First/Last per Group',
    'one-hot-encode': 'One-Hot Encode',
    'label-encode': 'Label Encode',
    'ordinal-encode': 'Ordinal Encode',
    'min-max-normalize': 'Min-Max Normalize',
    'z-score-standardize': 'Z-Score Standardize',
    'rolling-statistics': 'Rolling Statistics',
    'resample-timeseries': 'Resample Time Series',
    'regex-replace': 'Regex Replace',
    'expand-json-column': 'Expand JSON Column',
    'add-unique-id': 'Add Unique ID',
    'missing-indicator': 'Missing Value Indicator',
    'quantile-transform': 'Quantile Transform',
    // New Data Science Transform Blocks
    'fuzzy-join': 'Fuzzy Join',
    'memory-optimizer': 'Memory Optimizer',
    'cyclical-time-encoder': 'Cyclical Time Encoder',
    'geographic-distance': 'Geographic Distance',
    'rare-category-combiner': 'Rare Category Combiner',
    'smart-auto-cleaner': 'Smart Auto-Cleaner',
    'interaction-generator': 'Interaction Generator',
    'fuzzy-deduplicator': 'Fuzzy Deduplicator',
    'array-aggregator': 'Array Aggregator',
    'target-aware-binning': 'Target-Aware Binning',
    'statistics': 'Statistics',
    'regression': 'Regression',
    'clustering': 'Clustering',
    'pca': 'PCA',
    'outlier-detection': 'Outlier Detection',
    'classification': 'Classification',
    'normality-test': 'Normality Test',
    'hypothesis-testing': 'Hypothesis Testing',
    'time-series': 'Time Series',
    'feature-importance': 'Feature Importance',
    'cross-validation': 'Cross-Validation',
    'data-profiling': 'Data Profiling',
    'value-counts': 'Value Counts',
    'cross-tabulation': 'Cross-Tabulation',
    'scaling': 'Scaling',
    'encoding': 'Encoding',
    'ab-test': 'A/B Test',
    'cohort-analysis': 'Cohort Analysis',
    'rfm-analysis': 'RFM Analysis',
    'anova': 'ANOVA',
    'chi-square-test': 'Chi-Square Test',
    'correlation-analysis': 'Correlation Analysis',
    'survival-analysis': 'Survival Analysis',
    'association-rules': 'Association Rules',
    'sentiment-analysis': 'Sentiment Analysis',
    'moving-average': 'Moving Average',
    'train-test-split': 'Train/Test Split',
    'model-evaluation': 'Model Evaluation',
    'knn': 'K-Nearest Neighbors',
    'naive-bayes': 'Naive Bayes',
    'gradient-boosting': 'Gradient Boosting',
    'pareto-analysis': 'Pareto Analysis',
    'trend-analysis': 'Trend Analysis',
    'forecasting': 'Forecasting',
    'percentile-analysis': 'Percentile Analysis',
    'distribution-fit': 'Distribution Fit',
    'text-preprocessing': 'Text Preprocessing',
    'tfidf-vectorization': 'TF-IDF Vectorization',
    'topic-modeling': 'Topic Modeling',
    'similarity-analysis': 'Similarity Analysis',
    'svm': 'SVM',
    'xgboost': 'XGBoost',
    'model-explainability': 'Model Explainability (SHAP)',
    'regression-diagnostics': 'Regression Diagnostics',
    'vif-analysis': 'VIF Analysis',
    'funnel-analysis': 'Funnel Analysis',
    'customer-ltv': 'Customer Lifetime Value',
    'churn-analysis': 'Churn Prediction',
    'growth-metrics': 'Growth Metrics',
    'attribution-modeling': 'Attribution Modeling',
    'breakeven-analysis': 'Break-even Analysis',
    'confidence-intervals': 'Confidence Intervals',
    'bootstrap-analysis': 'Bootstrap Analysis',
    'posthoc-tests': 'Post-hoc Tests',
    'power-analysis': 'Power Analysis',
    'bayesian-inference': 'Bayesian Inference',
    'data-quality-score': 'Data Quality Score',
    'changepoint-detection': 'Change Point Detection',
    'isolation-forest': 'Isolation Forest',
    'arima-forecasting': 'ARIMA Forecasting',
    'seasonal-decomposition': 'Seasonal Decomposition',
    'monte-carlo-simulation': 'Monte Carlo Simulation',
    'propensity-score-matching': 'Propensity Score Matching',
    'difference-in-differences': 'Difference-in-Differences',
    'factor-analysis': 'Factor Analysis',
    'dbscan-clustering': 'DBSCAN Clustering',
    'elastic-net': 'Elastic Net',
    'var-analysis': 'VAR Analysis',
    'interrupted-time-series': 'Interrupted Time Series',
    'granger-causality': 'Granger Causality',
    'local-outlier-factor': 'Local Outlier Factor',
    'feature-selection': 'Feature Selection',
    'outlier-treatment': 'Outlier Treatment',
    'data-drift': 'Data Drift Detection',
    'polynomial-features': 'Polynomial Features',
    'multi-output': 'Multi-Output Prediction',
    'probability-calibration': 'Probability Calibration',
    'tsne-reduction': 't-SNE Reduction',
    'statistical-tests': 'Statistical Tests Suite',
    'optimal-binning': 'Optimal Binning',
    'correlation-finder': 'Correlation Finder',
    'ab-test-calculator': 'A/B Test Calculator',
    'target-encoding': 'Target Encoding',
    'learning-curves': 'Learning Curves',
    'imbalanced-data-handler': 'Imbalanced Data Handler',
    'hyperparameter-tuning': 'Hyperparameter Tuning',
    'ensemble-stacking': 'Ensemble Stacking',
    'advanced-imputation': 'Advanced Imputation',
    'umap-reduction': 'UMAP Reduction',
    'cluster-validation': 'Cluster Validation',
    'model-comparison': 'Model Comparison',
    'time-series-cv': 'Time Series CV',
    'uplift-modeling': 'Uplift Modeling',
    'quantile-regression': 'Quantile Regression',
    'adversarial-validation': 'Adversarial Validation',
    'custom-python-code': 'Custom Python Code',
    'sql-query': 'SQL Query',
    'auto-eda': 'Auto-EDA',
    'data-validation': 'Data Validation',
    'neural-network': 'Neural Network',
    'auto-feature-engineering': 'Auto Feature Engineering',
    'shap-interpretation': 'SHAP Interpretation',
    'automl': 'AutoML',
    'pipeline-export': 'Pipeline Export',
    'multivariate-anomaly': 'Multivariate Anomaly',
    'causal-impact': 'Causal Impact',
    'model-registry': 'Model Registry',
    // New Advanced Analysis Blocks for Data Scientists
    'comprehensive-eda': 'Comprehensive EDA Report',
    'shap-deep-explainer': 'SHAP Deep Explainer',
    'stl-decomposition': 'STL Time Series Decomposition',
    'multi-algorithm-anomaly': 'Multi-Algorithm Anomaly Detection',
    'automated-feature-pipeline': 'Automated Feature Engineering Pipeline',
    'distribution-drift-monitor': 'Distribution Drift Monitor',
    'smart-resampling': 'Smart Resampling for Imbalanced Data',
    'collinearity-diagnostics': 'Collinearity Diagnostics',
    'bayesian-ab-calculator': 'Bayesian A/B Test Calculator',
    'nested-cross-validation': 'Nested Cross-Validation',
    // New Pyodide-Compatible Analysis Blocks (December 2025)
    'gaussian-mixture-model': 'Gaussian Mixture Model',
    'dynamic-time-warping': 'Dynamic Time Warping',
    'lime-explainer': 'LIME Explainer',
    'bayesian-optimization': 'Bayesian Optimization',
    'time-series-features': 'Time Series Features',
    'robust-regression': 'Robust Regression',
    'kernel-density-estimation': 'Kernel Density Estimation',
    'spectral-clustering': 'Spectral Clustering',
    'cross-correlation': 'Cross-Correlation Analysis',
    'manifold-learning': 'Manifold Learning',
    'semi-supervised-learning': 'Semi-Supervised Learning',
    'multi-label-classification': 'Multi-Label Classification',
    'conformal-prediction': 'Conformal Prediction',
    'one-class-svm': 'One-Class SVM',
    'elliptic-envelope': 'Elliptic Envelope',
    'isotonic-regression': 'Isotonic Regression',
    'power-transform': 'Power Transform',
    'mutual-information-selection': 'Mutual Information Selection',
    'sequential-feature-selection': 'Sequential Feature Selection',
    'permutation-importance': 'Permutation Importance',
    'acf-pacf-analysis': 'ACF/PACF Analysis',
    'stationarity-testing': 'Stationarity Testing',
    'exponential-smoothing': 'Exponential Smoothing',
    'copula-analysis': 'Copula Analysis',
    'variance-threshold': 'Variance Threshold',
    'hierarchical-clustering': 'Hierarchical Clustering',
    'chart': 'Chart',
    'table': 'Table',
    'correlation-matrix': 'Correlation Matrix',
    'violin-plot': 'Violin Plot',
    'pair-plot': 'Pair Plot',
    'area-chart': 'Area Chart',
    'stacked-chart': 'Stacked Chart',
    'bubble-chart': 'Bubble Chart',
    'qq-plot': 'Q-Q Plot',
    'confusion-matrix': 'Confusion Matrix',
    'roc-curve': 'ROC Curve',
    'funnel-chart': 'Funnel Chart',
    'sankey-diagram': 'Sankey Diagram',
    'treemap': 'Treemap',
    'sunburst-chart': 'Sunburst Chart',
    'gauge-chart': 'Gauge Chart',
    'radar-chart': 'Radar Chart',
    'waterfall-chart': 'Waterfall Chart',
    'candlestick-chart': 'Candlestick Chart',
    'choropleth-map': 'Choropleth Map',
    'word-cloud': 'Word Cloud',
    'pareto-chart': 'Pareto Chart',
    'parallel-coordinates': 'Parallel Coordinates',
    'dendrogram': 'Dendrogram',
    'box-plot': 'Box Plot',
    'heatmap': 'Heatmap',
    'scatter-map': 'Scatter Map',
    'grouped-histogram': 'Grouped Histogram',
    'network-graph': 'Network Graph',
    'calendar-heatmap': 'Calendar Heatmap',
    'faceted-chart': 'Faceted Chart',
    'density-plot': 'Density Plot',
    'error-bar-chart': 'Error Bar Chart',
    'dot-plot': 'Dot Plot',
    'slope-chart': 'Slope Chart',
    'grouped-bar-chart': 'Grouped Bar Chart',
    'bump-chart': 'Bump Chart',
    'donut-chart': 'Donut Chart',
    'horizontal-bar-chart': 'Horizontal Bar Chart',
    'scatter-3d': '3D Scatter Plot',
    'contour-plot': 'Contour Plot',
    'hexbin-plot': 'Hexbin Plot',
    'ridge-plot': 'Ridge Plot',
    'strip-plot': 'Strip Plot',
    'bullet-chart': 'Bullet Chart',
    'pyramid-chart': 'Pyramid Chart',
    'timeline-chart': 'Timeline Chart',
    'surface-3d': '3D Surface Plot',
    'marginal-histogram': 'Marginal Histogram',
    'dumbbell-chart': 'Dumbbell Chart',
    // New Advanced Visualization Blocks for Data Scientists
    'shap-summary-plot': 'SHAP Summary Plot',
    'partial-dependence-plot': 'Partial Dependence Plot',
    'feature-importance-plot': 'Feature Importance Plot',
    'ice-plot': 'ICE Plot',
    'precision-recall-curve': 'Precision-Recall Curve',
    'learning-curve-plot': 'Learning Curve Plot',
    'residual-plot': 'Residual Plot',
    'actual-vs-predicted-plot': 'Actual vs Predicted Plot',
    'calibration-curve': 'Calibration Curve',
    'lift-chart': 'Lift Chart',
    'elbow-plot': 'Elbow Plot',
    'silhouette-plot': 'Silhouette Plot',
    'tsne-umap-plot': 't-SNE/UMAP Plot',
    'missing-value-heatmap': 'Missing Value Heatmap',
    'outlier-detection-plot': 'Outlier Detection Plot',
    'distribution-comparison-plot': 'Distribution Comparison',
    'ecdf-plot': 'ECDF Plot',
    'andrews-curves': 'Andrews Curves',
    'cv-results-plot': 'CV Results Plot',
    'hyperparameter-heatmap': 'Hyperparameter Heatmap',
    'export': 'Export',
  };
  return labels[type];
}

function getDefaultConfig(type: BlockType): Record<string, unknown> {
  const configs: Partial<Record<BlockType, Record<string, unknown>>> = {
    'load-data': { fileType: 'csv', encoding: 'utf-8', delimiter: 'auto' },
    'sample-data': { dataset: 'iris' },
    'create-dataset': { columns: 'name,age,city', data: 'Alice,30,New York\nBob,25,Los Angeles\nCharlie,35,Chicago' },
    'filter-rows': { column: '', operator: 'equals', value: '' },
    'select-columns': { columns: [], rename: {} },
    'sort': { columns: [], ascending: true },
    'group-aggregate': { groupBy: [], aggregations: {} },
    'join': { how: 'inner', leftOn: '', rightOn: '' },
    'derive-column': { newColumn: '', expression: '' },
    'handle-missing': { strategy: 'drop', fillValue: '', columns: [] },
    'rename-columns': { renames: {} },
    'deduplicate': { columns: [], keep: 'first' },
    'sample-rows': { sampleType: 'count', count: 100, fraction: 0.1, seed: null },
    'limit-rows': { position: 'first', count: 10 },
    'pivot': { index: '', columns: '', values: '', aggFunc: 'mean' },
    'unpivot': { idColumns: [], valueColumns: [], varName: 'variable', valueName: 'value' },
    'union': { ignoreIndex: true },
    'split-column': { column: '', delimiter: ',', newColumns: [], keepOriginal: false },
    'merge-columns': { columns: [], separator: ' ', newColumn: 'merged', keepOriginal: true },
    'conditional-column': { newColumn: '', condition: '', trueValue: '', falseValue: '' },
    'statistics': { type: 'descriptive', columns: [] },
    'regression': { type: 'linear', features: [], target: '' },
    'clustering': { algorithm: 'kmeans', nClusters: 3, features: [] },
    'pca': { nComponents: 2, features: [], scaleData: true },
    'outlier-detection': { method: 'iqr', threshold: 1.5, columns: [] },
    'classification': { algorithm: 'decision_tree', features: [], target: '', testSize: 0.2 },
    'normality-test': { method: 'shapiro', columns: [], alpha: 0.05 },
    'hypothesis-testing': { testType: 'ttest_ind', column1: '', column2: '', groupColumn: '', alpha: 0.05 },
    'time-series': { dateColumn: '', valueColumn: '', analysis: 'moving_average', windowSize: 7 },
    'feature-importance': { features: [], target: '', taskType: 'auto' },
    'cross-validation': { features: [], target: '', modelType: 'random_forest', taskType: 'auto', nFolds: 5 },
    'data-profiling': {},
    'value-counts': { column: '', normalize: false, sortBy: 'count', topN: 0 },
    'cross-tabulation': { rowColumn: '', colColumn: '', normalize: 'none', showTotals: true },
    'scaling': { columns: [], method: 'standard', keepOriginal: false },
    'encoding': { columns: [], method: 'onehot', dropFirst: false },
    'chart': { chartType: 'bar', x: '', y: '', color: '', title: '' },
    'table': { pageSize: 100, sortable: true, filterable: true },
    'correlation-matrix': { columns: [], method: 'pearson', showValues: true },
    'violin-plot': { column: '', groupColumn: '', title: '' },
    'pair-plot': { columns: [], colorColumn: '', maxColumns: 5 },
    'area-chart': { x: '', y: '', color: '', stacked: false, title: '' },
    'stacked-chart': { x: '', yColumns: [], chartType: 'bar', normalize: false, title: '' },
    'bubble-chart': { x: '', y: '', size: '', color: '', title: '' },
    'qq-plot': { column: '', title: '' },
    'confusion-matrix': { actualColumn: '', predictedColumn: '', normalize: false, title: '' },
    'roc-curve': { actualColumn: '', probabilityColumn: '', positiveClass: '', title: '' },
    'funnel-chart': { stageColumn: '', valueColumn: '', title: '', showPercentage: true, showDropoff: true },
    'sankey-diagram': { sourceColumn: '', targetColumn: '', valueColumn: '', title: '' },
    'treemap': { pathColumns: [], valueColumn: '', colorColumn: '', title: '' },
    'sunburst-chart': { pathColumns: [], valueColumn: '', title: '' },
    'gauge-chart': { valueColumn: '', minValue: 0, maxValue: 100, thresholds: [30, 70], colors: ['#EF4444', '#F59E0B', '#10B981'], title: '', suffix: '' },
    'radar-chart': { categoryColumn: '', valueColumns: [], title: '', fill: true },
    'waterfall-chart': { categoryColumn: '', valueColumn: '', title: '', showTotal: true },
    'candlestick-chart': { dateColumn: '', openColumn: '', highColumn: '', lowColumn: '', closeColumn: '', volumeColumn: '', title: '' },
    'choropleth-map': { locationColumn: '', valueColumn: '', locationType: 'usa-states', colorScale: 'Blues', title: '' },
    'word-cloud': { textColumn: '', weightColumn: '', maxWords: 100, minFontSize: 12, maxFontSize: 60, title: '' },
    'pareto-chart': { categoryColumn: '', valueColumn: '', title: '', showLine: true, show80Line: true },
    'parallel-coordinates': { columns: [], colorColumn: '', title: '' },
    'dendrogram': { columns: [], linkage: 'ward', distanceMetric: 'euclidean', orientation: 'top', colorThreshold: 0, title: '' },
    'box-plot': { column: '', groupColumn: '', title: '', showOutliers: true, notched: false },
    'heatmap': { xColumn: '', yColumn: '', valueColumn: '', colorScale: 'Blues', showValues: true, title: '' },
    'scatter-map': { latColumn: '', lonColumn: '', sizeColumn: '', colorColumn: '', title: '', mapStyle: 'open-street-map' },
    'grouped-histogram': { column: '', groupColumn: '', bins: 20, barMode: 'overlay', opacity: 0.7, title: '' },
    'network-graph': { sourceColumn: '', targetColumn: '', weightColumn: '', layout: 'force', title: '' },
    'calendar-heatmap': { dateColumn: '', valueColumn: '', colorScale: 'Greens', title: '' },
    'faceted-chart': { x: '', y: '', facetColumn: '', chartType: 'scatter', columns: 3, title: '' },
    'density-plot': { column: '', groupColumn: '', title: '', fillOpacity: 0.3 },
    'error-bar-chart': { categoryColumn: '', valueColumn: '', errorColumn: '', errorType: 'data', chartType: 'bar', title: '' },
    'dot-plot': { categoryColumn: '', valueColumn: '', colorColumn: '', orientation: 'horizontal', title: '' },
    'slope-chart': { entityColumn: '', startColumn: '', endColumn: '', startLabel: 'Before', endLabel: 'After', title: '' },
    'grouped-bar-chart': { categoryColumn: '', groupColumn: '', valueColumn: '', orientation: 'vertical', title: '' },
    'bump-chart': { entityColumn: '', timeColumn: '', rankColumn: '', title: '' },
    'donut-chart': { categoryColumn: '', valueColumn: '', title: '', holeSize: 0.4, showLabels: true, showPercent: true },
    'horizontal-bar-chart': { categoryColumn: '', valueColumn: '', colorColumn: '', sortBy: 'value', title: '' },
    'scatter-3d': { x: '', y: '', z: '', color: '', size: '', title: '' },
    'contour-plot': { x: '', y: '', colorScale: 'Blues', showLines: true, fillContours: true, title: '' },
    'hexbin-plot': { x: '', y: '', gridSize: 20, colorScale: 'Blues', title: '' },
    'ridge-plot': { valueColumn: '', categoryColumn: '', colorScale: 'Viridis', overlap: 0.5, title: '' },
    'strip-plot': { valueColumn: '', categoryColumn: '', jitter: 0.3, pointSize: 8, title: '' },
    'bullet-chart': { actualColumn: '', targetColumn: '', categoryColumn: '', ranges: [30, 70, 100], title: '' },
    'pyramid-chart': { categoryColumn: '', leftColumn: '', rightColumn: '', leftLabel: 'Left', rightLabel: 'Right', title: '' },
    'timeline-chart': { taskColumn: '', startColumn: '', endColumn: '', categoryColumn: '', title: '' },
    'surface-3d': { x: '', y: '', z: '', colorScale: 'Viridis', title: '' },
    'marginal-histogram': { x: '', y: '', color: '', bins: 20, title: '' },
    'dumbbell-chart': { categoryColumn: '', startColumn: '', endColumn: '', startLabel: 'Start', endLabel: 'End', title: '' },
    // New Advanced Visualization Blocks for Data Scientists
    'shap-summary-plot': { featureColumns: [], shapValuesColumn: '', maxFeatures: 20, plotType: 'dot', title: '' },
    'partial-dependence-plot': { featureColumn: '', targetColumn: '', gridResolution: 50, title: '' },
    'feature-importance-plot': { featureColumn: '', importanceColumn: '', maxFeatures: 20, sortOrder: 'descending', title: '' },
    'ice-plot': { featureColumn: '', targetColumn: '', nLines: 50, centered: false, title: '' },
    'precision-recall-curve': { actualColumn: '', probabilityColumn: '', positiveClass: '', title: '' },
    'learning-curve-plot': { trainScoreColumn: '', valScoreColumn: '', trainSizeColumn: '', title: '' },
    'residual-plot': { predictedColumn: '', actualColumn: '', showReferenceLine: true, title: '' },
    'actual-vs-predicted-plot': { actualColumn: '', predictedColumn: '', showPerfectLine: true, title: '' },
    'calibration-curve': { probabilityColumn: '', actualColumn: '', nBins: 10, title: '' },
    'lift-chart': { actualColumn: '', probabilityColumn: '', nBins: 10, title: '' },
    'elbow-plot': { kColumn: '', inertiaColumn: '', title: '' },
    'silhouette-plot': { clusterColumn: '', silhouetteColumn: '', title: '' },
    'tsne-umap-plot': { xColumn: '', yColumn: '', zColumn: '', colorColumn: '', labelColumn: '', title: '' },
    'missing-value-heatmap': { maxRows: 100, columns: [], title: '' },
    'outlier-detection-plot': { column: '', method: 'iqr', threshold: 1.5, title: '' },
    'distribution-comparison-plot': { valueColumn: '', groupColumn: '', bins: 30, title: '' },
    'ecdf-plot': { column: '', groupColumn: '', title: '' },
    'andrews-curves': { featureColumns: [], classColumn: '', nPoints: 100, title: '' },
    'cv-results-plot': { scoreColumns: [], foldColumn: '', modelColumn: '', title: '' },
    'hyperparameter-heatmap': { param1Column: '', param2Column: '', scoreColumn: '', aggregation: 'mean', title: '' },
    'export': { format: 'csv', filename: 'export' },
    'log-transform': { column: '', operation: 'log', handleZero: 'add_one', newColumn: '' },
    'interpolate-missing': { column: '', method: 'linear', orderColumn: '', limit: 0 },
    'date-truncate': { column: '', unit: 'day', newColumn: '' },
    'period-over-period': { dateColumn: '', valueColumn: '', period: 'mom', changeType: 'percent' },
    'hash-column': { column: '', algorithm: 'sha256', truncateLength: 0, newColumn: '' },
    'expand-date-range': { startColumn: '', endColumn: '', freq: 'D', groupColumns: [], fillMethod: 'ffill' },
    'string-similarity': { column1: '', column2: '', method: 'levenshtein', threshold: 0.8, newColumn: 'similarity' },
    'generate-sequence': { type: 'number', start: 1, end: 10, step: 1, columnName: 'sequence' },
    'top-n-per-group': { groupColumns: [], orderColumn: '', n: 5, ascending: false, includeRank: true },
    'first-last-per-group': { groupColumns: [], orderColumn: '', position: 'first' },
    'one-hot-encode': { columns: [], dropFirst: false, prefix: '', handleUnknown: 'error' },
    'label-encode': { columns: [], mappingOrder: 'alphabetical' },
    'ordinal-encode': { column: '', orderMapping: [], unknownValue: -1 },
    'min-max-normalize': { columns: [], featureRangeMin: 0, featureRangeMax: 1, suffix: '_normalized' },
    'z-score-standardize': { columns: [], withMean: true, withStd: true, suffix: '_standardized' },
    'rolling-statistics': { column: '', windowSize: 7, statistic: 'mean', minPeriods: 1, center: false },
    'resample-timeseries': { datetimeColumn: '', frequency: 'D', aggregation: 'mean', fillMethod: 'none' },
    'regex-replace': { column: '', pattern: '', replacement: '', caseInsensitive: false, replaceAll: true },
    'expand-json-column': { column: '', prefix: '', maxLevel: 1, keepOriginal: false },
    'add-unique-id': { idType: 'sequential', columnName: 'id', prefix: '', startFrom: 1 },
    'missing-indicator': { columns: [], suffix: '_missing', onlyIfMissing: true },
    'quantile-transform': { columns: [], outputDistribution: 'uniform', nQuantiles: 1000, suffix: '_quantile' },
    'isolation-forest': { columns: [], contamination: 0.1, nEstimators: 100, randomState: 42, outputColumn: 'is_anomaly' },
    'arima-forecasting': { dateColumn: '', valueColumn: '', order: [1, 1, 1], seasonalOrder: [0, 0, 0, 0], forecastPeriods: 10 },
    'seasonal-decomposition': { dateColumn: '', valueColumn: '', model: 'additive', period: 12 },
    'monte-carlo-simulation': { expression: '', variables: {}, nSimulations: 10000, randomState: 42 },
    'propensity-score-matching': { treatmentColumn: '', covariates: [], method: 'nearest', caliper: 0.2 },
    'difference-in-differences': { outcomeColumn: '', treatmentColumn: '', periodColumn: '', entityColumn: '' },
    'factor-analysis': { columns: [], nFactors: 3, rotation: 'varimax', method: 'principal' },
    'dbscan-clustering': { columns: [], eps: 0.5, minSamples: 5, metric: 'euclidean', outputColumn: 'cluster' },
    'elastic-net': { features: [], target: '', alpha: 1.0, l1Ratio: 0.5, maxIter: 1000, normalize: true },
    'var-analysis': { columns: [], maxLags: 10, criterion: 'aic', forecastPeriods: 10 },
    'interrupted-time-series': { dateColumn: '', valueColumn: '', interventionDate: '', segments: 2 },
    'granger-causality': { column1: '', column2: '', maxLag: 10, significanceLevel: 0.05 },
    'local-outlier-factor': { columns: [], nNeighbors: 20, contamination: 0.1, algorithm: 'auto', outputColumn: 'lof_score' },
    'feature-selection': { features: [], target: '', method: 'selectkbest', nFeatures: 10, scoreFunc: 'f_classif' },
    'outlier-treatment': { columns: [], method: 'iqr', action: 'cap', threshold: 1.5, lowerPercentile: 1, upperPercentile: 99 },
    'data-drift': { columns: [], method: 'ks_test', threshold: 0.05, psiBins: 10 },
    'polynomial-features': { columns: [], degree: 2, interactionOnly: false, includeBias: false },
    'multi-output': { features: [], targets: [], modelType: 'random_forest', taskType: 'auto', testSize: 0.2 },
    'probability-calibration': { probabilityColumn: '', actualColumn: '', method: 'isotonic', nBins: 10 },
    'tsne-reduction': { features: [], nComponents: 2, perplexity: 30, learningRate: 200, nIter: 1000 },
    'statistical-tests': { testType: 'mann_whitney', column1: '', column2: '', groupColumn: '', valueColumn: '', alpha: 0.05 },
    'optimal-binning': { column: '', target: '', method: 'quantile', nBins: 10, minBinSize: 0.05 },
    'correlation-finder': { columns: [], method: 'pearson', threshold: 0.7, showTopN: 20 },
    'ab-test-calculator': { testType: 'conversion', groupColumn: '', valueColumn: '', confidenceLevel: 0.95 },
    'target-encoding': { columns: [], target: '', smoothing: 10, minSamples: 1, handleUnknown: 'global_mean' },
    'learning-curves': { features: [], target: '', modelType: 'random_forest', taskType: 'auto', cvFolds: 5, trainSizes: [0.1, 0.2, 0.4, 0.6, 0.8, 1.0] },
    'imbalanced-data-handler': { targetColumn: '', method: 'smote', samplingStrategy: 'auto', kNeighbors: 5, randomState: 42 },
    'hyperparameter-tuning': { features: [], target: '', modelType: 'random_forest', taskType: 'auto', searchMethod: 'grid', cvFolds: 5, nIter: 20, scoringMetric: 'auto' },
    'ensemble-stacking': { features: [], target: '', baseModels: ['random_forest', 'logistic'], method: 'voting', votingType: 'soft', taskType: 'auto', testSize: 0.2 },
    'advanced-imputation': { columns: [], method: 'knn', nNeighbors: 5, maxIter: 10, randomState: 42 },
    'umap-reduction': { features: [], nComponents: 2, nNeighbors: 15, minDist: 0.1, metric: 'euclidean', randomState: 42 },
    'cluster-validation': { features: [], clusterColumn: '', includeProfile: true },
    'model-comparison': { features: [], target: '', models: ['random_forest', 'logistic', 'knn'], taskType: 'auto', testSize: 0.2, cvFolds: 5 },
    'time-series-cv': { features: [], target: '', dateColumn: '', modelType: 'random_forest', taskType: 'auto', nSplits: 5, gapSize: 0 },
    'uplift-modeling': { features: [], outcomeColumn: '', treatmentColumn: '', method: 't_learner' },
    'quantile-regression': { features: [], target: '', quantiles: [0.1, 0.5, 0.9], method: 'gradient_boosting' },
    'adversarial-validation': { trainData: 'train', splitColumn: '', trainValue: '', testValue: '', features: [] },
    'custom-python-code': { code: '# Write your Python code here\n# Input data is available as `df`\n# Config is available as `config`\n# You must assign the result to `output`\n\noutput = df', timeout: 30000 },
    'sql-query': { query: 'SELECT * FROM df1', inputCount: 1 },
    'auto-eda': { outputFormat: 'json', includeCorrelations: true, includeDistributions: true, includeMissing: true, includeOutliers: true },
    'data-validation': { rules: [], failOnError: false, outputInvalidRows: true },
    'neural-network': { features: [], target: '', taskType: 'classification', hiddenLayers: [64, 32], activation: 'relu', optimizer: 'adam', learningRate: 0.001, epochs: 100, batchSize: 32, validationSplit: 0.2, earlyStoppingPatience: 10 },
    'auto-feature-engineering': { features: [], maxInteractionDepth: 2, generatePolynomial: true, generateInteractions: true, generateDateFeatures: true, generateTextFeatures: false },
    'shap-interpretation': { modelColumn: '', features: [], explanationType: 'global', nSamples: 100, plotType: 'summary' },
    'automl': { features: [], target: '', taskType: 'auto', timeBudget: 60, models: ['random_forest', 'xgboost', 'lightgbm', 'logistic', 'knn'], cvFolds: 5, optimizeMetric: 'auto' },
    'pipeline-export': { outputFormat: 'script', includeComments: true, includeRequirements: true, filename: 'pipeline' },
    'multivariate-anomaly': { features: [], algorithm: 'isolation_forest', contamination: 0.1, outputScores: true, outputFlags: true },
    'causal-impact': { outcomeColumn: '', treatmentColumn: '', preInterventionPeriod: '', postInterventionPeriod: '', method: 'did', controlGroup: '' },
    'model-registry': { action: 'save', modelName: '', modelVersion: '1.0', modelDescription: '', modelId: '' },
    // New Pyodide-Compatible Analysis Blocks (December 2025)
    'gaussian-mixture-model': { features: [], nComponents: 3, covarianceType: 'full', maxIter: 100, randomState: 42, outputProbabilities: true, outputCluster: true },
    'dynamic-time-warping': { series1Column: '', series2Column: '', groupColumn: '', windowSize: 0, outputDistance: true },
    'lime-explainer': { features: [], target: '', modelType: 'random_forest', taskType: 'auto', instanceIndex: 0, nFeatures: 10, nSamples: 500 },
    'bayesian-optimization': { features: [], target: '', modelType: 'random_forest', taskType: 'auto', nIterations: 20, randomState: 42 },
    'time-series-features': { valueColumn: '', groupColumn: '', includeBasic: true, includeAutocorrelation: true, includeEntropy: true, includeTrend: true },
    'robust-regression': { features: [], target: '', method: 'huber', testSize: 0.2, randomState: 42 },
    'kernel-density-estimation': { columns: [], kernel: 'gaussian', bandwidth: 'auto', nPoints: 100, outputDensity: true },
    'spectral-clustering': { features: [], nClusters: 3, affinity: 'rbf', nNeighbors: 10, randomState: 42 },
    'cross-correlation': { series1Column: '', series2Column: '', maxLag: 20, normalize: true },
    'manifold-learning': { features: [], method: 'isomap', nComponents: 2, nNeighbors: 10, randomState: 42 },
    'semi-supervised-learning': { features: [], targetColumn: '', method: 'label-propagation', kernel: 'rbf', gamma: 20, nNeighbors: 7, maxIter: 1000 },
    'multi-label-classification': { features: [], targetColumns: [], method: 'classifier-chain', baseEstimator: 'logistic', randomState: 42 },
    'conformal-prediction': { features: [], targetColumn: '', coverageLevel: 0.9, method: 'split', calibrationSize: 0.2, taskType: 'classification' },
    'one-class-svm': { features: [], kernel: 'rbf', nu: 0.1, gamma: 'scale' },
    'elliptic-envelope': { features: [], contamination: 0.1, supportFraction: null, randomState: 42 },
    'isotonic-regression': { featureColumn: '', targetColumn: '', increasing: 'auto', outOfBounds: 'clip' },
    'power-transform': { features: [], method: 'yeo-johnson', standardize: true },
    'mutual-information-selection': { features: [], targetColumn: '', taskType: 'classification', nNeighbors: 3, topK: 10, randomState: 42 },
    'sequential-feature-selection': { features: [], targetColumn: '', direction: 'forward', nFeaturesToSelect: 'auto', taskType: 'classification', cv: 5 },
    'permutation-importance': { features: [], targetColumn: '', taskType: 'classification', nRepeats: 10, randomState: 42 },
    'acf-pacf-analysis': { valueColumn: '', maxLags: 40, alpha: 0.05 },
    'stationarity-testing': { valueColumn: '', testType: 'both', regressionType: 'c', maxLags: 'auto' },
    'exponential-smoothing': { valueColumn: '', trend: 'add', seasonal: 'none', seasonalPeriods: 12, forecastPeriods: 10, alpha: 0.3, beta: 0.1, gamma: 0.1 },
    'copula-analysis': { column1: '', column2: '', copulaType: 'gaussian', nSamples: 1000 },
    'variance-threshold': { features: [], threshold: 0.0, normalizeFirst: true },
    'hierarchical-clustering': { features: [], nClusters: 3, linkage: 'ward', metric: 'euclidean', computeDistances: true },
  };
  return configs[type] || {};
}

export const useCanvasStore = create<CanvasState>()(
  temporal(
    (set, get) => ({
      blocks: [],
      edges: [],
      selectedBlockIds: [],
      viewport: { x: 0, y: 0, zoom: 1 },

      addBlock: (type, position) => {
        const id = uuidv4();
        set((state) => ({
          blocks: [
            ...state.blocks,
            {
              id,
              type: 'custom',
              position,
              data: {
                type,
                category: getBlockCategory(type),
                label: getBlockLabel(type),
                config: getDefaultConfig(type),
                state: 'idle',
              },
            },
          ],
        }));
        return id;
      },

      addBlockDirect: (block) => {
        set((state) => {
          // Check if block already exists
          if (state.blocks.some((b) => b.id === block.id)) {
            return state;
          }
          return {
            blocks: [...state.blocks, block],
          };
        });
      },

      updateBlock: (id, data) => {
        set((state) => ({
          blocks: state.blocks.map((block) =>
            block.id === id
              ? { ...block, data: { ...block.data, ...data } }
              : block
          ),
        }));
      },

      removeBlock: (id) => {
        set((state) => ({
          blocks: state.blocks.filter((b) => b.id !== id),
          edges: state.edges.filter((e) => e.source !== id && e.target !== id),
          selectedBlockIds: state.selectedBlockIds.filter((i) => i !== id),
        }));
      },

      setBlockState: (id, blockState) => {
        set((state) => ({
          blocks: state.blocks.map((block) =>
            block.id === id
              ? { ...block, data: { ...block.data, state: blockState } }
              : block
          ),
        }));
      },

      addEdge: (source, target, sourceHandle, targetHandle) => {
        const id = `${source}-${target}`;
        set((state) => {
          if (state.edges.find((e) => e.id === id)) {
            return state;
          }
          return {
            edges: [
              ...state.edges,
              { id, source, target, sourceHandle, targetHandle, type: 'animated' },
            ],
          };
        });
      },

      addEdgeDirect: (edge) => {
        set((state) => {
          // Check if edge already exists
          if (state.edges.some((e) => e.id === edge.id)) {
            return state;
          }
          return {
            edges: [...state.edges, edge],
          };
        });
      },

      removeEdge: (id) => {
        set((state) => ({
          edges: state.edges.filter((e) => e.id !== id),
        }));
      },

      setBlocks: (blocks) => {
        set({ blocks });
      },

      setEdges: (edges) => {
        set({ edges });
      },

      setSelectedBlocks: (ids) => {
        set({ selectedBlockIds: ids });
      },

      clearSelection: () => {
        set({ selectedBlockIds: [] });
      },

      setViewport: (viewport) => {
        set({ viewport });
      },

      importPipeline: (blocks, edges) => {
        set({ blocks, edges });
      },

      clearCanvas: () => {
        set({
          blocks: [],
          edges: [],
          selectedBlockIds: [],
        });
      },
    }),
    {
      limit: 100,
    }
  )
);
